# Generated by Django 4.0 on 2021-12-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wall_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wall',
            old_name='title',
            new_name='message',
        ),
    ]
